version: '3.3'

services:
  database:
    image: mongo:3.4-jessie
    networks:
      - default
    ports:
    - 27017
    volumes:
    - db_data:/data/db
    restart: always

  defichain:
    build: ./defichain
    networks: 
      - default
    ports:
      - 8555
      - 8554
      - 18555
      - 18554
      - 19555
      - 19554
    volumes:
      - node_data:/data
      - ./defichain/defi.testnet.conf:/root/.defi/defi.conf

  bitcore-node:
    build: .
    image: bitcore-node
    # network_mode: host
    networks:
      - default
    command: "bash -c 'cd ./packages/bitcore-node/; npm run tsc; node build/src/server.js'"
    ports:
      - 3000:3000
    environment:
      - DB_HOST=database
      - NETWORK=testnet
      - CHAIN=DFI
      - BITCORE_CONFIG_PATH=bitcore.config.json
    volumes: 
      - ./bitcore.config.json:/usr/src/app/bitcore.config.json
    depends_on:
      - database
      - defichain
    restart: always

  insight:
    build: .
    image: insight
    # network_mode: host
    networks:
      - default
    command: ["npm", "run", "insight-previous:prod"]
    ports:
      - 80:5000
    environment:
      - ENV=prod
      - NETWORK=testnet
      - CHAIN=DFI
      - API_PREFIX=http://explorer.defichain.io:3000/api
      - BITCORE_CONFIG_PATH=bitcore.config.json
    volumes: 
      - ./bitcore.config.json:/usr/src/app/bitcore.config.json
    depends_on:
      - bitcore-node
    restart: always

volumes: 
  db_data:
  node_data:
