version: '3'
services:
  database:
    image: mongo:3.4-jessie
    # network_mode: host
    networks:
      - default
    ports:
    - 27017:27017
    volumes:
    - /data/db2:/data/db
    restart: always

  bitcore-node:
    build: .
    image: bitcore-node
    # network_mode: host
    networks:
      - default
    command: ["npm", "run", "node"]
    ports:
      - 3000:3000
    environment:
      - DB_HOST=database
      - NETWORK=testnet
      - CHAIN=DFI
      - BITCORE_CONFIG_PATH=bitcore.config.json
    depends_on:
      - database
    restart: always

  insight:
    build: .
    image: insight
    # network_mode: host
    networks:
      - default
    command: ["npm", "run", "insight-previous:prod"]
    ports:
      - 8200:5000
    environment:
      - ENV=prod
      - NETWORK=testnet
      - CHAIN=DFI
      - API_PREFIX=http://127.0.0.1:3000/api
      - BITCORE_CONFIG_PATH=bitcore.config.json
    depends_on:
      - bitcore-node
    restart: always
